"""empty message

Revision ID: e717f95e7e7f
Revises:
Create Date: 2016-05-19 16:13:25.016463

"""

# revision identifiers, used by Alembic.
revision = 'e717f95e7e7f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from pgcontents.utils.migrations import execute_sql_files

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine=u'innodb',
    mysql_row_format=u'DYNAMIC'
    )
    op.create_table('directories',
    sa.Column('user_id', sa.Unicode(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=300), nullable=False),
    sa.Column('parent_user_id', sa.Unicode(length=30), nullable=True),
    sa.Column('parent_name', sa.Unicode(length=300), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id', 'parent_name'], [u'directories.user_id', u'directories.name'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'name'),
    mysql_engine=u'innodb',
    mysql_row_format=u'DYNAMIC'
    )
    op.create_table('remote_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=30), nullable=False),
    sa.Column('path', sa.Unicode(length=300), nullable=False),
    sa.Column('content', sa.LargeBinary(length=100000), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine=u'innodb',
    mysql_row_format=u'DYNAMIC'
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=300), nullable=False),
    sa.Column('user_id', sa.Unicode(length=30), nullable=False),
    sa.Column('parent_name', sa.Unicode(length=300), nullable=False),
    sa.Column('content', sa.LargeBinary(length=100000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'parent_name'], [u'directories.user_id', u'directories.name'], onupdate=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_name', 'name', name=u'uix_filepath_username'),
    mysql_engine=u'innodb',
    mysql_row_format=u'DYNAMIC'
    )
    ### end Alembic commands ###

    execute_sql_files(op, 'directories_check_constraint_trigger/0001_initial_version.sql')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('remote_checkpoints')
    op.drop_table('directories')
    op.drop_table('users')
    ### end Alembic commands ###

    execute_sql_files(op, 'directories_check_constraint_trigger/0000_deleted.sql')
